version: '3.8'

services:
  backend:
    image: shitoletushar3132/shorturl-backend
    expose:
      - "3000"
    depends_on:
      - redis
    networks:
      - app-net
    deploy:
      mode: replicated
      replicas: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
